### ISSUE TITLE
Feature Request %7C NAME OF REQUEST

### ISSUE THREAD

**Issue by jayjay176** [ownagepe/Updates#11]
kev and gd whatever there name is , they seem to want us to talk trash about them considering the fact that they start arguments with members and when we have sum to say we get muted or kicked . muted for racism when i’m black . lmfaoaoaoa

**Comment by Zedstar16** [comment]
Does not matter if you are black as we don’t have a way of confirming that.
Therefore any racial slurs are not acceptable under any circumstances
