### ISSUE TITLE
Unclaiming bug

### ISSUE THREAD

**Issue by Galqctus** [ownagepe/Updates#13]
**Bug Description:** Thid bug is that my fac have a claim then it keeps unclaiming every day, and now someone found it and claimed it while the bug happened

**Servers Affected:** The servers affected by the bug. It is technically a cheat for the people in my fac.

**How to reproduce the bug** We dont know how it happens but whenever we get on after school it happens but when I got on yesterday it had been claimed by someone fac "Amense" and we worked so hard on it, to be glitched and claimed by a faction that has a jrmod as a leader and we allied to them I haven't got any chance to speak to Amense leader yet.

**Proof of Bug:** We do not have any proof of it happening but it still did happen and we have lost everything because of this glitch :/

**Comment by Olybear9** [comment]
Unfortunately this is not descriptive enough to mark this as a bug. Try making sure your faction officers didn't unclaim it or something like that.
