### ISSUE TITLE
Feature Request | Clear Lag

### ISSUE THREAD

**Issue by TopUnderRqted** [ownagepe/Updates#14]
A Countdown for Clear Lag

A countdown for clear lag, for example. It tells you when the clear lag will happen starting from 30 minutes to 20 minutes to 10 minutes to 5 minutes to 30 seconds that way players don’t lose their stuff when trying to trade 

Cuboss has this, it could prevent players from losing their items

Players might quit if they drop their stuff to trade or to show someone something and it clear lags. Therefore, if you add the countdown, they’ll be aware and wait till the countdown is over and no one loses their stuff unless they get scammed

**Comment by ManiakMCPE** [comment]
Added! Thank you for the suggestion.
