### ISSUE TITLE
Idea by JR

### ISSUE THREAD

**Issue by TheJRbeast** [ownagepe/Updates#15]
I was thinking from a server which is now basically dying and was extremely fun which had 70 players at its highest point. What if we like did a lucky block faction server. where protection wouldn’t work. As well as sharpness. Only ces worked. The pvp would also be like a combo where you could get like 3 hits per sec or something which can kill u with egap.Sounds broken but trust me that’s what made the server fun. Until it became pay to win. For more detail dm me :)) u know my discord

**Comment by UserAsleep** [comment]
lol

**Comment by Olybear9** [comment]
Please follow the format when making a feature request.
