### ISSUE TITLE
Major STR Glitch | Factions 

### ISSUE THREAD

**Issue by yxkev** [ownagepe/Updates#16]
**Bug Description:** Gives ANY faction UNLIMITED Str 

**Servers Affected: Factions

**How to reproduce the bug:** 
> Steps transferred to private issue

**Proof of Bug:** Video - PLEASE NOTE THE VIDEO WAS BEING TESTED AND RECORDED FOR REPORTING CONCERNS! 2 ACTIVE STAFF WERE IN THE CALL WHILE PERFORMING THIS!

**Comment by Olybear9** [comment]
Thank you for reporting this issue! Our developer team has resolved the issue!
