### ISSUE TITLE
FIX LAG FFS

### ISSUE THREAD

**Issue by nickalyn** [ownagepe/Updates#18]
FIX PRACTICE LAG, we can’t make dam people fly CSU’s did the lag then you get people with 500+ lag that beat the good players just that that CSU’s did their lag and the servers lag. I’m sick of playing with this lag cause yourll moves to a freaking cheaper host looks lik.

**Comment by Olybear9** [comment]
If you're going to bash the server, at least make a valid request, and follow the format
