### ISSUE TITLE
Anti-STR Farming

### ISSUE THREAD

**Issue by Olybear9** [ownagepe/Updates#3]
**Recreate STR system:**
- [x] Base STR from KDR of the player
- [x] Lower KDRx3 if a player is killed. (On Factions) 
- [x] Implement a STR handler

**Comment by Olybear9** [comment]
Should Anti-STR farming reset after the player is kicked?

**REPLY BELOW**

**Comment by Zedstar16** [comment]
no

**Comment by SwaggersTheKid** [comment]
Ok so I recommend you make it so when a Player dies 5-10 times they will have a 1 hour cooldown were who ever kills them they will not gain str but they can still loose str from dying.

**Comment by Olybear9** [comment]
> Ok so I recommend you make it so when a Player dies 5-10 times they will have a 1 hour cooldown were who ever kills them they will not gain str but they can still loose str from dying.

The ANTI-STR system will be banning a player for an hour if they STR farm. However, there will be a check, where every 30 minutes to an hour where it will clear the violations list.

**Comment by Zedstar16** [comment]
> > Ok so I recommend you make it so when a Player dies 5-10 times they will have a 1 hour cooldown were who ever kills them they will not gain str but they can still loose str from dying.
> 
> The ANTI-STR system will be banning a player for an hour if they STR farm. However, there will be a check, where every 30 minutes to an hour where it will clear the violations list.

What happens if a player is simply trying to defend their base from a player who keeps returning to a home they have set?
I think that simply disabling the gain of strength would be sufficient, as a player could use the fact that the defending player will get banned, as an opportunity to raid without interference when the defender does get banned

**Comment by UserAsleep** [comment]
Hmm..

Perhaps you could change it to count player KDR or player deaths and have that number determine how much str they are worth

**Comment by Olybear9** [comment]
> > > Ok so I recommend you make it so when a Player dies 5-10 times they will have a 1 hour cooldown were who ever kills them they will not gain str but they can still loose str from dying.
> > 
> > 
> > The ANTI-STR system will be banning a player for an hour if they STR farm. However, there will be a check, where every 30 minutes to an hour where it will clear the violations list.
> 
> What happens if a player is simply trying to defend their base from a player who keeps returning to a home they have set?
> I think that simply disabling the gain of strength would be sufficient, as a player could use the fact that the defending player will get banned, as an opportunity to raid without interference when the defender does get banned

Thanks for the suggestion, I will be reworking the STR system to make it compatible with this request.

**Comment by Zedstar16** [comment]
> Hmm..
> 
> Perhaps you could change it to count player KDR or player deaths and have that number determine how much str they are worth

Dynamic strength gain seems like a pretty good idea actually.
As a player would gain more str from killing a skilled player instead of one that simply jumps into the arena naked all the time

**Comment by Olybear9** [comment]
Thanks for the suggestions, we will be going with @UserAsleep suggestion with Dynamic Strength, you can check the progress of this update by looking at this issue.

**Comment by ManiakMCPE** [comment]
Added to the server
