### ISSUE TITLE
Feature Request | Age of a player

### ISSUE THREAD

**Issue by Entety101** [ownagepe/Updates#7]
The How Old command

Can you add a command that you can type that determines the age of a player based on their grammar, sentence structure, and words they use? Example: /howold (player_name) (Results)

KitPvP, Factions, SkyBlock, and the Ownage Discord

It might encourage players to be more mature in chat. I think it would be a cool feature.

**Comment by Olybear9** [comment]
Hello, Thanks for your suggestion! We will be looking at this suggestion further to see what we can do.
