### ISSUE TITLE
Add invis barriers around warp pvp in factions so people cant jump off and go to spawn Feature Request | Server Suggestion

### ISSUE THREAD

**Issue by Teader202** [ownagepe/Updates#8]
**Suggestion Title:** A short name for the request.

**Suggestion Description:** A long description on what you are asking us.

**Servers Affected:** List of servers affected by the request.

**How you think it will improve ownage:** (Not required, but highly recommended.)

**Comment by Olybear9** [comment]
Please fill out the format in the issue before opening one.

**Comment by Olybear9** [comment]
Thank you for the suggestion!
